### ISSUE TITLE
Can you use your repo to do some job in Florence2 language model?

### ISSUE THREAD

**Issue by zydjohnHotmail** [dansav/clip-sharp#4]
Hi, 
I have one screenshot, I want to use Florence2 to do some job like: 
REGION_TO_SEGMENTATION or REGION_PROPOSAL
But currently I can use Florence2 to get only one Region, which is not enough, I need at least 5 regions (the dogs) or more (some people and other objects).
I want to know if this CLIP language model has the similar tasks, like: REGION_TO_SEGMENTATION or REGION_PROPOSAL, and if possible, can you run your repo with the screenshot I uploaded here, and let me know how many regions you can get with your repo.
Thanks,
![GBHAR01](https://github.com/user-attachments/assets/5ce8ab8e-2975-4a0f-8784-faf5ec55db0e)

**Comment by dansav** [comment]
Thank you for your interest in clip-sharp. I don't think this repo can solve what you're trying to achieve. The CLIP model is designed to associate images with textual descriptions, enabling tasks like image classification and image-text similarity matching. It doesn't support region-based tasks, segmentation, or object proposals, such as identifying multiple objects within a single image.

**Comment by zydjohnHotmail** [comment]
OK. Thanks!
